// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyhnetmrtchzbvsvqyeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95aG5ldG1ydGNoemJ2c3ZxeWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTE3ODMsImV4cCI6MjA2ODMyNzc4M30.z7DE-BkvPHA-YyFDYSVi6Q1CJs7gvfTB_sMMIQiNzZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});